version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./sessions:/var/www/html/sessions
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mukticar_banking
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"

volumes:
  db_data:
